In [1]:
from bbi.environments import GoRight
import numpy as np

In [ ]:
env = GoRight(has_state_offset=False)
# env = SamplingModel(has_state_offset=False)
env.reset()
# env.set_state(state=np.array([0.0, 10.0, 0.0, 0.0]), previous_status=10)

In [ ]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 0., 0., 0.]), -1.0, False, False, {})

In [129]:
env.step(1)

(array([10., 10.,  1.,  1.]), -1.0, False, False, {})

In [26]:
env.step(0)

(array([9., 5., 0., 0.], dtype=float32), 0.0, False, False, {})

In [31]:
count = 0
initial = 0.0
for _ in range(100_000):
    initial += env.step(1)[0]
    count += 1

initial / count

array([10.     ,  5.0058 ,  0.33333,  0.33333], dtype=float32)

In [41]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 0.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  0.])

In [47]:
env.step(1)

(array([10.,  0.,  0.,  0.]), -1.0, False, False, {})

In [54]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 1.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  1.])

In [58]:
env.step(1)

(array([10.,  5.,  0.,  0.]), -1.0, False, False, {})

In [1]:
from bbi.models import ExpectationModel

env = ExpectationModel(has_state_offset=False)
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [2]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 5., 0., 0.], dtype=float32), -1.0, False, False, {})

In [9]:
env.step(1)

(array([10.,  5.,  0.,  0.], dtype=float32), -1.0, False, False, {})

In [38]:
env.step(0)

(array([9., 5., 0., 0.], dtype=float32), 0.0, False, False, {})