In [22]:
from bbi.models import SamplingModel
from bbi.environments import GoRight
import numpy as np

In [23]:
env = SamplingModel(has_state_offset=False)
env.reset()

(array([ 0., 10.,  0.,  0.], dtype=float32), {})

In [24]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 0., 0., 0.], dtype=float32), -1.0, False, False, {})

In [46]:
env.step(1)

(array([10.,  0.,  1.,  1.], dtype=float32), -1.0, False, False, {})

In [47]:
env.step(1)

(array([10.,  0.,  1.,  1.], dtype=float32), 3.0, False, False, {})

In [20]:
env.set_state(
    state=np.array([10.0, 5.0, 0.0, 0.0]),
    previous_status=0
)
env.state

array([10.,  5.,  0.,  0.])

In [21]:
env.step(1)

(array([10.,  5.,  1.,  0.]), -1.0, False, False, {})