In [5]:
from bbi.models import SamplingModel
import numpy as np

In [12]:
# env = GoRight(has_state_offset=False)
env = SamplingModel(has_state_offset=False)
env.reset()
# env.set_state(state=np.array([0.0, 10.0, 0.0, 0.0]), previous_status=10)

(array([0., 0., 0., 0.], dtype=float32), {})

In [13]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 0., 0., 0.], dtype=float32), -1.0, False, False, {})

In [14]:
count = 0
initial = 0.0
for _ in range(100_000):
    initial += env.step(1)[0]  # going to position 10
    env.step(0)  # returning to pos 9
    count += 1

initial / count

array([10.     ,  4.99185,  0.33679,  0.3353 ], dtype=float32)

In [41]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 0.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  0.])

In [47]:
env.step(1)

(array([10.,  0.,  0.,  0.]), -1.0, False, False, {})

In [54]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 1.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  1.])

In [58]:
env.step(1)

(array([10.,  5.,  0.,  0.]), -1.0, False, False, {})

In [15]:
from bbi.models import ExpectationModel

env = ExpectationModel(has_state_offset=False)
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [16]:
env.set_state(state=[10, 0, 1, 1], previous_status=0)

In [20]:
env.step(1)

([np.int64(10), 5, np.int64(1), np.int64(1)], 3.0, False, False, {})

In [2]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 5., 0., 0.], dtype=float32), -1.0, False, False, {})

In [9]:
env.step(1)

(array([10.,  5.,  0.,  0.], dtype=float32), -1.0, False, False, {})

In [38]:
env.step(0)

(array([9., 5., 0., 0.], dtype=float32), 0.0, False, False, {})

In [14]:
from bbi.models import BBI

In [15]:
env = BBI()
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [35]:
state, reward, _, _, _ = env.step(1)
print("State:", state, "\nReward: ", reward, "\n")
print(
    "State BB:\n",
    "Upper bound: ",
    env.state_bounding_box[1],
    "\n Lower bound: ",
    env.state_bounding_box[0],
    "\n",
)
print("Reward BB:\n", env.reward_bounding_box, "\n")

State: [10.  5.  1.  0.] 
Reward:  -1.0 

State BB:
 Upper bound:  [10. 10.  1.  1.] 
 Lower bound:  [10.  0.  1.  0.] 

Reward BB:
 [-1.0, 3.0] 



In [1]:
from bbi.environments import GoRight

/Users/lucruz/Documents/GitHub/research-sandbox/.venv/lib/python3.10/site-packages/pygame/pkgdata.py:25: UserWarning: Module bbi was already imported from None, but /Users/lucruz/Documents/GitHub/research-sandbox is being added to sys.path
  from pkg_resources import resource_stream, resource_exists


In [2]:
env = GoRight()
env.reset()

(array([ 0.15617523,  1.2241955 , -0.2476423 , -0.02469329], dtype=float32),
 {})

In [9]:
env.set_state_from_rounded([10.0, 2, 3], previous_status=0)
env.state

array([10., 10.,  1.,  1.])

In [11]:
env.step(1)

(array([10.15617522,  6.22419545,  0.7523577 ,  0.97530671]),
 3.0,
 False,
 False,
 {})

In [29]:
import numpy as np

a = [np.array([0.0, 1.0]), np.array([1.0, 0.0])]

In [30]:
np.min(a, axis=0)

array([0., 0.])