In [130]:
from bbi.models import SamplingModel
import numpy as np

In [131]:
# env = GoRight(has_state_offset=False)
env = SamplingModel(has_state_offset=False)
env.reset()
# env.set_state(state=np.array([0.0, 10.0, 0.0, 0.0]), previous_status=10)

(array([0., 5., 0., 0.], dtype=float32), {})

In [132]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 5., 0., 0.], dtype=float32), -1.0, False, False, {})

In [129]:
env.step(1)

(array([10., 10.,  1.,  1.]), -1.0, False, False, {})

In [134]:
env.step(0)

(array([9., 0., 0., 0.], dtype=float32), 0.0, False, False, {})

In [135]:
count = 0
initial = 0.0
for _ in range(100_000):
    initial += env.step(1)[0]  # going to position 10
    env.step(0)  # returning to pos 9
    count += 1

initial / count

array([10.     ,  5.016  ,  0.33359,  0.33646], dtype=float32)

In [41]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 0.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  0.])

In [47]:
env.step(1)

(array([10.,  0.,  0.,  0.]), -1.0, False, False, {})

In [54]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 1.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  1.])

In [58]:
env.step(1)

(array([10.,  5.,  0.,  0.]), -1.0, False, False, {})

In [1]:
from bbi.models import ExpectationModel

env = ExpectationModel(has_state_offset=False)
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [2]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 5., 0., 0.], dtype=float32), -1.0, False, False, {})

In [9]:
env.step(1)

(array([10.,  5.,  0.,  0.], dtype=float32), -1.0, False, False, {})

In [38]:
env.step(0)

(array([9., 5., 0., 0.], dtype=float32), 0.0, False, False, {})

In [14]:
from bbi.models import BBI

In [15]:
env = BBI()
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [35]:
state, reward, _, _, _ = env.step(1)
print("State:", state, "\nReward: ", reward, "\n")
print(
    "State BB:\n",
    "Upper bound: ",
    env.state_bounding_box[1],
    "\n Lower bound: ",
    env.state_bounding_box[0],
    "\n",
)
print("Reward BB:\n", env.reward_bounding_box, "\n")

State: [10.  5.  1.  0.] 
Reward:  -1.0 

State BB:
 Upper bound:  [10. 10.  1.  1.] 
 Lower bound:  [10.  0.  1.  0.] 

Reward BB:
 [-1.0, 3.0] 

