In [130]:
from bbi.models import SamplingModel
import numpy as np

In [131]:
# env = GoRight(has_state_offset=False)
env = SamplingModel(has_state_offset=False)
env.reset()
# env.set_state(state=np.array([0.0, 10.0, 0.0, 0.0]), previous_status=10)

(array([0., 5., 0., 0.], dtype=float32), {})

In [132]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 5., 0., 0.], dtype=float32), -1.0, False, False, {})

In [129]:
env.step(1)

(array([10., 10.,  1.,  1.]), -1.0, False, False, {})

In [134]:
env.step(0)

(array([9., 0., 0., 0.], dtype=float32), 0.0, False, False, {})

In [135]:
count = 0
initial = 0.0
for _ in range(100_000):
    initial += env.step(1)[0]  # going to position 10
    env.step(0)  # returning to pos 9
    count += 1

initial / count

array([10.     ,  5.016  ,  0.33359,  0.33646], dtype=float32)

In [41]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 0.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  0.])

In [47]:
env.step(1)

(array([10.,  0.,  0.,  0.]), -1.0, False, False, {})

In [54]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 1.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  1.])

In [58]:
env.step(1)

(array([10.,  5.,  0.,  0.]), -1.0, False, False, {})

In [1]:
from bbi.models import ExpectationModel

env = ExpectationModel(has_state_offset=False)
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [2]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([9., 5., 0., 0.], dtype=float32), -1.0, False, False, {})

In [9]:
env.step(1)

(array([10.,  5.,  0.,  0.], dtype=float32), -1.0, False, False, {})

In [38]:
env.step(0)

(array([9., 5., 0., 0.], dtype=float32), 0.0, False, False, {})

In [1]:
from bbi.models import BBI

/Users/lucruz/Documents/GitHub/research-sandbox/.venv/lib/python3.10/site-packages/pygame/pkgdata.py:25: UserWarning: Module bbi was already imported from None, but /Users/lucruz/Documents/GitHub/research-sandbox is being added to sys.path
  from pkg_resources import resource_stream, resource_exists


In [3]:
env = BBI()
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [13]:
env.step(1)

(array([[10.,  0.,  0.,  0.],
        [10., 10.,  1.,  1.]]),
 array([-1.,  3.]),
 False,
 False,
 {})