In [48]:
import numpy as np

from bbi.models import SamplingModel

In [49]:
env = SamplingModel(has_state_offset=False)
env.reset()

(array([0., 5., 0., 0.], dtype=float32), {})

In [87]:
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)
env.step(1)

(array([10., 10.,  0.,  1.], dtype=float32), -1.0, False, False, {})

In [85]:
env.step(1)

(array([10.,  5.,  1.,  1.], dtype=float32), 3.0, False, False, {})

In [86]:
env.step(0)

(array([ 9., 10.,  0.,  0.], dtype=float32), 0.0, False, False, {})

In [20]:
env.set_state(state=np.array([10.0, 5.0, 0.0, 0.0]), previous_status=0)
env.state

array([10.,  5.,  0.,  0.])

In [21]:
env.step(1)

(array([10.,  5.,  1.,  0.]), -1.0, False, False, {})